# Generated by Django 5.1 on 2024-09-07 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('subscribers', models.ManyToManyField(blank=True, to='notify.address')),
            ],
        ),
        migrations.AddField(
            model_name='address',
            name='subscriptions',
            field=models.ManyToManyField(blank=True, to='notify.device'),
        ),
    ]
